[Desktop Entry]
Name=Yaru-sage
Type=X-GNOME-Metatheme
Comment=Ubuntu Yaru-sage theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Yaru-sage
MetacityTheme=Yaru
IconTheme=Yaru-sage
CursorTheme=Yaru
CursorSize=24
X-Yaru-Dark=false
X-Yaru-Accent-Name=sage
X-Yaru-Accent-Color=#657B69
/Users/lnbodicherla/Documents/gnome-nautilus/_build_deps/yaru-24.10.1/build/gtk/src/Yaru-sage-sage-accent-color-info.scss:46 DEBUG: Contrast optimized accent is #889d8c
