[Desktop Entry]
Name=Yaru-purple-dark
Type=X-GNOME-Metatheme
Comment=Ubuntu Yaru-purple-dark theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Yaru-purple-dark
MetacityTheme=Yaru-dark
IconTheme=Yaru-purple-dark
CursorTheme=Yaru
CursorSize=24
X-Yaru-Dark=true
X-Yaru-Accent-Name=purple
X-Yaru-Accent-Color=#7764D8
/Users/lnbodicherla/Documents/gnome-nautilus/_build_deps/yaru-24.10.1/build/gtk/src/Yaru-purple-dark-purple-accent-color-info.scss:46 DEBUG: Contrast optimized accent is #7562d7
