[Desktop Entry]
Name=Yaru-red
Type=X-GNOME-Metatheme
Comment=Ubuntu Yaru-red theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Yaru-red
MetacityTheme=Yaru
IconTheme=Yaru-red
CursorTheme=Yaru
CursorSize=24
X-Yaru-Dark=false
X-Yaru-Accent-Name=red
X-Yaru-Accent-Color=#DA3450
/Users/lnbodicherla/Documents/gnome-nautilus/_build_deps/yaru-24.10.1/build/gtk/src/Yaru-red-red-accent-color-info.scss:46 DEBUG: Contrast optimized accent is #e67588
