[Desktop Entry]
Name=Yaru-olive-dark
Type=X-GNOME-Metatheme
Comment=Ubuntu Yaru-olive-dark theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Yaru-olive-dark
MetacityTheme=Yaru-dark
IconTheme=Yaru-olive-dark
CursorTheme=Yaru
CursorSize=24
X-Yaru-Dark=true
X-Yaru-Accent-Name=olive
X-Yaru-Accent-Color=#4B8501
/Users/lnbodicherla/Documents/gnome-nautilus/_build_deps/yaru-24.10.1/build/gtk/src/Yaru-olive-dark-olive-accent-color-info.scss:46 DEBUG: Contrast optimized accent is #498101
