[Desktop Entry]
Name=Yaru-blue
Type=X-GNOME-Metatheme
Comment=Ubuntu Yaru-blue theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Yaru-blue
MetacityTheme=Yaru
IconTheme=Yaru-blue
CursorTheme=Yaru
CursorSize=24
X-Yaru-Dark=false
X-Yaru-Accent-Name=blue
X-Yaru-Accent-Color=#0073E5
/Users/lnbodicherla/Documents/gnome-nautilus/_build_deps/yaru-24.10.1/build/gtk/src/Yaru-blue-blue-accent-color-info.scss:46 DEBUG: Contrast optimized accent is #369bff
