[Desktop Entry]
Name=Yaru-olive
Type=X-GNOME-Metatheme
Comment=Ubuntu Yaru-olive theme
Encoding=UTF-8

[X-GNOME-Metatheme]
GtkTheme=Yaru-olive
MetacityTheme=Yaru
IconTheme=Yaru-olive
CursorTheme=Yaru
CursorSize=24
X-Yaru-Dark=false
X-Yaru-Accent-Name=olive
X-Yaru-Accent-Color=#4B8501
/Users/lnbodicherla/Documents/gnome-nautilus/_build_deps/yaru-24.10.1/build/gtk/src/Yaru-olive-olive-accent-color-info.scss:46 DEBUG: Contrast optimized accent is #60aa01
